#! /bin/sh

if [ $(hostname) = "workstation" ]; then
    bspc monitor DVI-I-1 -n main
    bspc monitor DVI-D-0 -n secondary
    bspc monitor main -d 0 2 4 6 8
    bspc monitor secondary -d 1 3 5 7 9
elif [ $(hostname) = "thinkpad" ]; then
    bspc monitor LVDS1 -n main
    bspc monitor main -d 0 1 2 3 4 5 6 7 8 9
fi

bspc config border_width         2
bspc config window_gap           4

bspc config top_padding          $PANEL_HEIGHT
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner


bspc rule -a Firefox desktop='^3'
bspc rule -a mpv state=floating
