#!/usr/bin/env bash

shopt -s nullglob globstar

dmenu_notify() {
	: | timelimit -t 3 -T 5 dmenu -p "$1"
}

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
    dmenu_notify "Password copied to clipboard, you have 45 seconds."
else
	xdotool - <<<"type --clearmodifiers --delay 0 -- "$(pass show "$password" | head -n 1)""
fi
